version: 2
lint-debounce: 1s

tools:
  import-sort: &import-sort
    root-markers:
      - node_modules/import-sort/
    format-command: '~/scripts/import-sort-always-stdout.sh ${INPUT}'

  prettier: &prettier
    root-markers:
      - node_modules/prettier/
    format-command: './node_modules/.bin/prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  stylish-haskell: &stylish-haskell
    root-markers:
      - cabal.project
    format-command: 'stylish-haskell ${INPUT}'
    format-stdin: true

languages:
  haskell:
    - <<: *stylish-haskell
  javascript:
    - <<: *import-sort
    - <<: *prettier
  typescript:
    - <<: *import-sort
    - <<: *prettier
  typescriptreact:
    - <<: *import-sort
    - <<: *prettier
