name: Check

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      - run: nix flake check

  fmt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
      # https://github.com/NixOS/nix/issues/6908
      - run: nix develop -c bash -c 'nixpkgs-fmt --check .'
